### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by yashp386** [krutikgami/TrimUR#1]
![image](https://github.com/user-attachments/assets/257305b5-7aec-4012-9c97-493ed2e17e2a)
@krutikgami

**Comment by krutikgami** [comment]
> ![image](https://github.com/user-attachments/assets/257305b5-7aec-4012-9c97-493ed2e17e2a)
> @krutikgami 

Due to not properly host backend on vercel.Under maintenance
